version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: vista_magazijn
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    image: php:8.3-apache
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: vista_magazijn
      DB_USER: appuser
      DB_PASS: apppass
      JWT_SECRET: local-secret-key
    ports:
      - "8080:80"

volumes:
  db_data:
